import 'package:flutter/material.dart';

class AppStrings {
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'settings': 'Settings',
      'language': 'Language',
      'choose_dialect': 'Choose your preferred dialect',
      'notifications': 'Notifications',
      'dark_mode': 'Dark Mode',
      'save_changes': 'Save Changes',
      'settings_saved': 'Settings saved successfully',
      'skip': 'Skip',
      'next': 'Next',
      'get_started': 'Get Started',
      'onboarding1_title1': 'Welcome to\n',
      'onboarding1_title2': 'Thao Nguyen\nResort',
      'onboarding1_desc':
          'Experience the mist-veiled sanctuary of Moc Chau, where the lush tea hills meet eco-luxury comfort.',
      'onboarding2_title': 'Luxury in Harmony\nwith Nature',
      'onboarding2_desc':
          'Enjoy world-class services amidst green\nlandscapes.',
      'onboarding3_title': 'Seamless\nExperience',
      'onboarding3_desc':
          'Book your stay and pay securely with\nMoMo in just a few taps.',
      'welcome_back': 'Welcome Back',
      'login_subtitle': 'Enter your credentials to access your sanctuary.',
      'phone_email_label': 'PHONE NUMBER OR EMAIL',
      'email_hint': 'e.g., Example@email.com',
      'password_label': 'PASSWORD',
      'password_hint': 'Enter password',
      'forgot_password': 'Forgot password?',
      'login': 'Login',
      'or_continue_with': 'OR CONTINUE WITH',
      'login_with_google': 'Login with Google',
      'no_account': "Don't have an account? ",
      'register': 'Register',
      'login_error_email_empty': 'Please enter email or phone number.',
      'login_error_email_invalid': 'Invalid email or phone number format.',
      'login_error_password_empty': 'Please enter password.',
      'login_error_password_short': 'Password must be at least 8 characters.',
      'login_failed': 'Login failed.',
      'cannot_connect_server': 'Cannot connect to server. Please try again.',
      'verify_account_title': 'Verify Account',
      'verify_account_msg':
          'Your account is not verified.\nPlease verify your account to continue.',
      'cancel': 'Cancel',
      'verify_now': 'Verify Now',
      'step_x_of_3': 'STEP {step} OF 3',
      'create_account': 'Create\nAccount',
      'register_subtitle':
          'Begin your journey into the Moc Chau sanctuary. Your forest hideaway awaits.',
      'full_name_label': 'FULL NAME',
      'full_name_hint': 'Enter Full Name',
      'email_address_label': 'EMAIL ADDRESS',
      'phone_number_label': 'PHONE NUMBER',
      'phone_hint': '+84 000 000 000',
      'already_have_account': 'Already have an account? ',
      'log_in': 'LOG IN',
      'secure_your_stay': 'Secure your\nstay.',
      'password_subtitle':
          'Choose a password to protect your account\nand bookings.',
      'confirm_password_label': 'CONFIRM PASSWORD',
      're_enter_password_hint': 'Re-enter password',
      'char_8_plus': '8+ Characters',
      'special_symbol': 'Special symbol',
      'save_for_later': 'SAVE FOR LATER',
      'register_error_name_empty': 'Please enter your full name.',
      'register_error_name_invalid':
          'Full name can only contain letters and spaces.',
      'register_error_email_empty': 'Please enter your email.',
      'register_error_email_invalid': 'Invalid email format.',
      'register_error_phone_empty': 'Please enter your phone number.',
      'register_error_phone_invalid':
          'Phone number must start with 0 or +84 and have 10 digits.',
      'register_error_password_empty': 'Please enter a password.',
      'register_error_password_short':
          'Password must be at least 8 characters long.',
      'register_error_password_special':
          'Password must contain at least one special character.',
      'register_error_confirm_empty': 'Please confirm your password.',
      'register_error_confirm_mismatch': 'Confirm password does not match.',
      'register_failed': 'Registration failed.',
      'cannot_connect_server': 'Cannot connect to server.',
      'final_review': 'Final Review',
      'final_review_subtitle':
          'Please ensure all details are correct\nbefore finalizing your membership.',
      'personal_details': 'PERSONAL DETAILS',
      'edit': 'Edit',
      'agree_to_terms': 'I agree to the ',
      'terms_of_sanctuary': 'Terms of Sanctuary',
      'and_acknowledge':
          ' and\nacknowledge the privacy policy\nregarding forest conservation.',
      'submit': 'Submit',
      'home': 'Home',
      'bookings': 'Bookings',
      'services': 'Services',
      'profile': 'Profile',
      'search': 'Search',
      'welcome': 'WELCOME TO THE HIGHLANDS',
      'hello': 'Hello',
      'rooms': 'Rooms',
      'view_all': 'View All',
      'popular_rooms': 'Popular Rooms',
      'night': 'night',
      'per_night': '/ night',
      'booking_history': 'Booking History',
      'payment_history': 'Payment History',
      'about_resort': 'About Resort',
      'contact_us': 'Contact Us',
      'location': 'Location',
      'logout': 'Logout',
      'edit_profile': 'Edit Profile',
      'full_name': 'Full Name',
      'email': 'Email Address',
      'phone': 'Phone Number',
      'dob': 'Date of Birth',
      'gender': 'Gender',
      'address': 'Address',
      'cancel': 'Cancel',
      'save': 'Save',
      'categories': 'Categories',
      'popular_stays': 'Popular Stays',
      'search_hint': 'Search experiences...',
      'all': 'All',
      'promotion': 'PROMOTION',
      'adults': 'Adults',
      'children': 'Children',
      'amenities': 'AMENITIES',
      'show_less': 'Show less ∧',
      'more_amenities': 'More amenities ∨',
      'the_sanctuary_experience': 'THE SANCTUARY EXPERIENCE',
      'read_more': 'Read more ˇ',
      'available_rooms': 'AVAILABLE ROOMS',
      'selected': 'selected',
      'choose_room_instruction': 'Choose the room you want to book',
      'more_room_numbers': 'More room numbers ∨',
      'stay_summary': 'STAY SUMMARY',
      'edit': 'EDIT',
      'room_charge': 'Room Charge',
      'room_numbers': 'Room Numbers',
      'children_extra_fee': 'Children Extra Fee',
      'service_fee_taxes': 'Service Fee & Taxes (10%)',
      'total': 'Total',
      'select_date_room_instruction': 'Please select dates & rooms',
      'select_date_instruction': 'Please select stay dates',
      'select_room_instruction': 'Please select a room',
      'max_rooms_error': 'Maximum 2 rooms can be booked at once!',
      'no_description': 'No description available.',
      'no_rooms_available': 'Currently no rooms available.',
      'male': 'Male',
      'female': 'Female',
      'other': 'Other',
      'profile_updated': 'Profile updated successfully',
      'update_failed': 'Update failed',
      'error_occurred': 'An error occurred',
      'nights': 'Nights',
      'change_photo': 'CHANGE PHOTO',
      'email_address': 'EMAIL ADDRESS',
      'phone_number': 'PHONE NUMBER',
      'date_of_birth': 'DATE OF BIRTH',
      'required': 'Required',
      'email_change_support': 'Contact support to change verified email.',
      'select': 'Select',
      'my_bookings': 'My Bookings',
      'pending': 'Pending',
      'confirmed': 'Confirmed',
      'completed': 'Completed',
      'no_bookings_found': 'No bookings found',
      'login_to_view_history': 'Please login to view booking history',
      'retry': 'Retry',
      'failed_load_bookings': 'Failed to load bookings',
      'portfolio_overview': 'PORTFOLIO OVERVIEW',
      'total_spent': 'Total Spent',
      'all_payments': 'All Payments',
      'last_30_days': 'Last 30 Days',
      'refunds': 'Refunds',
      'no_transactions_found': 'No transactions found',
      'failed_load_rooms': 'Failed to load rooms',
      'all_rooms': 'All rooms',
      'no_rooms_found': 'No rooms found',
      'adjust_filters': 'Try adjusting your filters',
      'resort_services': 'Resort Services',
      'nourish_soul': 'Nourish your soul and senses',
      'exclusives': 'EXCLUSIVES',
      'curated_experiences': 'Curated Experiences',
      'hall': 'Hall',
      'food': 'Food',
      'event': 'Event',
      'hall_desc': 'Grand ballroom & conference rooms',
      'food_desc': 'Fine dining & local specialties',
      'event_desc': 'Weddings, parties & festivals',
      'other_services_desc': 'Guided tours & special activities',
      'hall_cap': 'Up to 500 guests',
      'food_cap': 'Gourmet experience',
      'event_cap': 'Custom arrangements',
      'other_cap': 'Daily adventures',
      'check_in': 'Check-in',
      'check_out': 'Check-out',
      'quantity': 'Quantity',
      'room_price': 'Room Price',
      'stay_summary_title': 'Your Stay Summary',
      'qr_pass': 'Your QR Pass',
      'voucher_applied': 'VOUCHER APPLIED',
      'taxes_service_fee': 'Taxes & Service Fee (10%)',
      'total_amount': 'Total Amount',
      'no_booking_data': 'No booking data found',
      'booking_details': 'Booking Details',
      'digital_checkin_pass': 'DIGITAL CHECK-IN PASS',
      'accommodation_details': 'Accommodation Details',
      'billing_summary': 'Billing Summary',
      'pricing_summary': 'Pricing Summary',
      'primary_guest': 'PRIMARY GUEST',
      'modify_booking': 'MODIFY BOOKING',
      'cancellation_policy': 'Free cancellation until',
      'loyalty_points_label': 'LOYALTY POINTS',
      'total_stays_label': 'TOTAL STAYS',
      'management': 'MANAGEMENT',
      'others': 'OTHERS',
      'resort_info': 'RESORT INFO',
      'contact': 'Contact',
      'get_in_touch': 'GET IN TOUCH',
      'call_now': 'Call Now',
      'send_email': 'Send Email',
      'inquiry_form': 'Inquiry Form',
      'submit_inquiry': 'Submit Inquiry',
      'your_message': 'YOUR MESSAGE',
      'resort_address': 'RESORT ADDRESS',
      'our_sanctuary': 'OUR SANCTUARY',
      'get_directions': 'Get Directions',
      'open_google_maps': 'Open in Google Maps',
      'request_pickup': 'Request Pickup',
      'from': 'From',
      'twin': 'Twin',
      'double': 'Double',
      'triple': 'Triple',
      'villa': 'Villa',
      'no_results_found': 'No results found',
      'about_service': 'About the Service',
      'service_packages': 'Service Packages',
      'atmosphere': 'Atmosphere',
      'grand_venue': 'GRAND VENUE',
      'premium_service': 'PREMIUM SERVICE',
      'book_service': 'Book Service',
      'total_estimate': 'TOTAL ESTIMATE',
      'guests_label': 'Guests',
      'daily_hourly': 'Daily / Hourly',
      'flexible_timing': 'Flexible Timing',
      'unlimited': 'Unlimited',
      'full_day_pkg': 'Full Day Package',
      'half_day_pkg': 'Half Day Package',
      'standard_unit': 'Standard Unit',
      'per': 'Per',
      'choose_date': 'Choose Date',
      'popular': 'Popular',
      'above_12': 'Above 12 years old',
      'below_12': 'Below 12 years old',
      'child_age_label': 'CHILD {n} AGE',
      'age_less_6': '< 6 years old',
      'age_6_12': '6 - 12 years old',
      'age_more_12': '> 12 years old',
      'continue': 'Continue',
      'max_capacity_reached': 'Maximum {max} {label} reached',
      'edit_booking': 'Edit Booking',
      'current_reservation': 'CURRENT RESERVATION',
      'select_dates': 'SELECT DATES',
      'select_dates_error': 'Please select Check-in and Check-out dates!',
      'extra_fee_breakfast_note': '*Children extra fee includes breakfast.',
      'update_booking': 'Update Booking',
      'premium_eco_luxury': 'PREMIUM ECO-LUXURY',
      'resort_tagline':
          'A sanctuary carved into the emerald slopes of the Moc Chau highlands, where the mist of the morning meets the luxury of intentional design.',
      'resort_philosophy':
          'Our philosophy centers on "The Digital Conservatory" — a belief that modern living should coexist harmoniously with the organic world. At Thao Nguyen Resort, we\'ve replaced rigid boundaries with flowing spaces and sustainable materials that reflect the verdant landscape of northern Vietnam.\n\nExperience the quiet prestige of the highlands, where every detail is curated to provide a sanctuary from the digital noise of the outside world.',
      'nature_inspired_title': 'Nature-inspired design',
      'nature_inspired_desc':
          'Architecture that breathes with the mountains, utilizing local wood and stone to mirror the natural terrain.',
      'premium_services_title': 'Premium services',
      'premium_services_desc':
          'Bespoke concierge care and world-class culinary experiences that celebrate highland heritage.',
      'peaceful_atmosphere_title': 'Peaceful atmosphere',
      'peaceful_atmosphere_desc':
          'Quiet zones and meditation spaces designed to restore your inner rhythm and clarity.',
      'amenities_overview': 'AMENITIES OVERVIEW',
      'infinity_pool': 'Infinity Forest Pool',
      'infinity_pool_desc': 'Heated mountain-spring water',
      'organic_dining': 'Organic Dining',
      'highland_spa': 'Highland Spa',
      'mountain_biking': 'Complimentary Mountain Biking',
      'contact_headline': "We're here to help\nyou find your\npeace.",
      'inquiry_form_subtitle':
          'Leave a message and our concierge will contact you shortly.',
      'message_hint': 'How can we assist your stay?',
      'location_headline': 'Moc Chau, Son La,\nVietnam',
      'location_desc':
          'Nestled in the misty highlands of Northern Vietnam, surrounded by verdant tea hills and blooming plum blossoms.',
      'highland_access': 'Highland Access',
      'travel_time': '4 hours from Hanoi',
      'find_sanctuary': 'Find Sanctuary',
      'reset': 'RESET',
      'your_stay': 'YOUR STAY',
      'checkin_out': 'Check-in & Out',
      'arrival': 'ARRIVAL',
      'departure': 'DEPARTURE',
      'select_date': 'Select Date',
      'capacity': 'CAPACITY',
      'num_guests': 'Number of Guests',
      'ages_13_above': 'Ages 13 or above',
      'ages_2_12': 'Ages 2 - 12',
      'zone': 'Zone',
      'all_zones': 'All Zones',
      'investment': 'INVESTMENT',
      'price_range': 'Price Range',
      'minimum': 'MINIMUM',
      'maximum': 'MAXIMUM',
      'search_sanctuaries': 'SEARCH SANCTUARIES',
      'search_error_msg':
          'Please select Check-in, Check-out dates and number of adults!',
      'failed_load_rooms': 'Failed to load rooms',
      'no_rooms_found': 'No rooms found',
      'adjust_filters': 'Try adjusting your filters',
      'found_n_sanctuaries': 'Found {n} Sanctuaries',
      'filter': 'FILTER',
      'price': 'PRICE',
      'filters': 'Filters',
      'clear_all': 'Clear All',
      'room_type': 'ROOM TYPE',
      'all_room_types': 'All Room Types',
      'apply_filters': 'Apply Filters',
      'left_count': '{n} LEFT',
      'adults_count': '{n} Adults',
      'children_count': '{n} Children',
      'select_services': 'Select Services',
      'no_services_available': 'No services available.',
      'no_dates_selected': 'No dates selected',
      'from_price_unit': 'From {price} VND / {unit}',
      'stay_summary_title': 'STAY SUMMARY',
      'room_charge_n_nights':
          'Room Charge ({n_rooms} room × {n_nights} nights)',
      'room_numbers': 'Room Numbers',
      'children_extra_fee': 'Children Extra Fee',
      'services_total': 'Services Total',
      'service_fee_tax': 'Service Fee & Taxes (10%)',
      'final_amount': 'FINAL AMOUNT',
      'continue': 'Continue',
      'review_booking': 'Review Booking',
      'selected_retreat': 'SELECTED RETREAT',
      'from_2pm': 'from 2:00 PM',
      'until_12pm': 'until 12:00 PM',
      'travelers_accommodation': 'TRAVELERS & ACCOMMODATION',
      'n_rooms_count': '{n} Room',
      'n_rooms_count_plural': '{n} Rooms',
      'selected_services_title': 'SELECTED SERVICES',
      'quantity': 'Quantity',
      'price_breakdown': 'PRICE BREAKDOWN',
      'discount_code': 'DISCOUNT CODE',
      'enter_code': 'Enter code',
      'apply': 'APPLY',
      'applied': 'APPLIED',
      'terms_disclaimer':
          'By tapping "Pay Now" you agree to Thao Nguyen Resort\'s Terms of Service and Cancellation Policy.',
      'voucher_applied_msg': 'Voucher applied successfully',
      'invalid_voucher_msg': 'Invalid voucher code',
      'discount_label': 'Discount ({code})',
      'total_amount_label': 'Total Amount',
      'select_payment_method': 'SELECT PAYMENT METHOD',
      'bank_transfer': 'Bank Transfer',
      'instant_local_transfer': 'Instant Local Transfer',
      'e_wallet': 'E-Wallet',
      'credit_card': 'Credit Card',
      'cash_label': 'Cash',
      'pay_at_front_desk': 'Pay at front desk',
      'secure_checkout': 'SECURE ENCRYPTED CHECKOUT',
      'coming_soon': 'Coming Soon',
      'pay_now': 'Pay Now',
      'failed_create_booking': 'Failed to create booking',
      'terms_of_use': 'Terms of Use',
      'pay_now_agreement':
          'By clicking "Pay Now", you agree to Thao Nguyen Resort\'s ',
      'room_number_label': 'Room Number: {n}',
      'n_rooms_m_nights': '{n} room(s) ({m} night(s))',
      'room_number_label': 'Room Number: {n}',
      'n_rooms_m_nights': '{n} room(s) ({m} night(s))',
      'service_tax_label': 'Service Fee & Taxes (10%)',
      'room_label': 'Room',
      'room_price_label': 'Room Price',
      'booking_confirmed': 'Booking Confirmed!',
      'sanctuary_awaits': 'Your sanctuary awaits.',
      'reservation_id_label': 'RESERVATION ID',
      'paid_status': 'PAID',
      'view_booking_btn': 'View Booking',
      'back_to_home_btn': 'Back to Home',
      'secure_reservation_system': 'SECURE RESERVATION SYSTEM',
      'resort_service_label': 'Thao Nguyen Resort • Service',
      'resort_nights_label': 'Thao Nguyen Resort • {n} Night(s)',
      'service_booking_date': 'Service Booking Date',
      'num_portions': 'Number of Portions',
      'select_portions_instruction': 'Please select number of portions',
      'confirm_booking_btn': 'CONFIRM BOOKING',
      'secure_payment_msg': 'SECURE PAYMENT POWERED BY SANCTUARYPAY',
      'server_error_msg': 'Server connection error',
      'total_price': 'Total Price',
      'resort_room': 'Resort Room',
      'resort_service': 'Resort Service',
      'service_details': 'Service Details',
      'extra_services_included': 'Extra Services Included',
      'quantity_portions': 'Quantity/Portions',
      'unit_price': 'Unit Price',
      'amount_label': 'Amount',
      'subtotal_label': 'Subtotal',
      'room_number_label': 'Room Number(s)',
      'portfolio_overview': 'PORTFOLIO OVERVIEW',
      'total_spent': 'Total Spent',
      'all_payments': 'All Payments',
      'last_30_days': 'Last 30 Days',
      'refunds': 'Refunds',
      'no_transactions_found': 'No transactions found',
      'paid_status': 'PAID',
      'failed_status': 'FAILED',
      'refunded_status': 'REFUNDED',
      'account_preferences': 'ACCOUNT PREFERENCES',
    },
    'vi': {
      'settings': 'Cài đặt',
      'language': 'Ngôn ngữ',
      'choose_dialect': 'Chọn ngôn ngữ bạn muốn sử dụng',
      'notifications': 'Thông báo',
      'dark_mode': 'Chế độ tối',
      'save_changes': 'Lưu thay đổi',
      'settings_saved': 'Đã lưu cài đặt thành công',
      'skip': 'Bỏ qua',
      'next': 'Tiếp tục',
      'get_started': 'Bắt đầu ngay',
      'onboarding1_title1': 'Chào mừng bạn đến với\n',
      'onboarding1_title2': 'Thao Nguyen\nResort',
      'onboarding1_desc':
          'Trải nghiệm không gian nghỉ dưỡng kết hợp tham quan đồi chè xanh mướt tại Mộc Châu cùng với sự tiện nghi sang trọng.',
      'onboarding2_title': 'Sự sang trọng hòa quyện\ncùng thiên nhiên',
      'onboarding2_desc':
          'Tận hưởng dịch vụ đẳng cấp thế giới giữa\ncảnh quan hùng vĩ của núi rừng Tây Bắc.',
      'onboarding3_title': 'Trải nghiệm\ntuyệt vời',
      'onboarding3_desc':
          'Đặt phòng và thanh toán nhanh chóng chỉ với vài thao tác.',
      'welcome_back': 'Chào mừng trở lại',
      'login_subtitle':
          'Nhập thông tin của bạn để truy cập vào không gian nghỉ dưỡng.',
      'phone_email_label': 'SỐ ĐIỆN THOẠI HOẶC EMAIL',
      'email_hint': 'Ví dụ: Example@email.com',
      'password_label': 'MẬT KHẨU',
      'password_hint': 'Nhập mật khẩu',
      'forgot_password': 'Quên mật khẩu?',
      'login': 'Đăng nhập',
      'or_continue_with': 'HOẶC TIẾP TỤC VỚI',
      'login_with_google': 'Đăng nhập với Google',
      'no_account': 'Chưa có tài khoản? ',
      'register': 'Đăng ký',
      'login_error_email_empty': 'Vui lòng nhập email hoặc số điện thoại.',
      'login_error_email_invalid':
          'Email hoặc số điện thoại không đúng định dạng.',
      'login_error_password_empty': 'Vui lòng nhập mật khẩu.',
      'login_error_password_short': 'Mật khẩu phải có ít nhất 8 ký tự.',
      'login_failed': 'Đăng nhập thất bại.',
      'cannot_connect_server':
          'Không thể kết nối đến server. Vui lòng thử lại.',
      'verify_account_title': 'Xác thực tài khoản',
      'verify_account_msg':
          'Tài khoản của bạn chưa được xác thực.\nVui lòng xác thực tài khoản để tiếp tục.',
      'cancel': 'Hủy',
      'verify_now': 'Xác thực ngay',
      'step_x_of_3': 'BƯỚC {step} / 3',
      'create_account': 'Tạo\nTài khoản',
      'register_subtitle':
          'Bắt đầu hành trình của bạn tại Mộc Châu. Nơi nghỉ dưỡng lý tưởng đang chờ đón bạn.',
      'full_name_label': 'HỌ VÀ TÊN',
      'full_name_hint': 'Nhập họ và tên',
      'email_address_label': 'ĐỊA CHỈ EMAIL',
      'phone_number_label': 'SỐ ĐIỆN THOẠI',
      'phone_hint': '+84 000 000 000',
      'already_have_account': 'Đã có tài khoản? ',
      'log_in': 'ĐĂNG NHẬP',
      'secure_your_stay': 'Bảo mật\ntài khoản.',
      'password_subtitle':
          'Chọn mật khẩu để bảo vệ tài khoản\nvà các thông tin đặt phòng của bạn.',
      'confirm_password_label': 'XÁC NHẬN MẬT KHẨU',
      're_enter_password_hint': 'Nhập lại mật khẩu',
      'char_8_plus': '8+ ký tự',
      'special_symbol': 'Ký tự đặc biệt',
      'save_for_later': 'LƯU ĐỂ SAU',
      'register_error_name_empty': 'Vui lòng nhập họ tên.',
      'register_error_name_invalid': 'Họ tên chỉ chứa chữ cái và dấu cách.',
      'register_error_email_empty': 'Vui lòng nhập email.',
      'register_error_email_invalid': 'Email không đúng định dạng.',
      'register_error_phone_empty': 'Vui lòng nhập số điện thoại.',
      'register_error_phone_invalid':
          'SĐT phải bắt đầu bằng 0 hoặc +84, gồm 10 số.',
      'register_error_password_empty': 'Vui lòng nhập mật khẩu.',
      'register_error_password_short': 'Mật khẩu phải có ít nhất 8 ký tự.',
      'register_error_password_special':
          'Mật khẩu phải chứa ít nhất 1 ký tự đặc biệt.',
      'register_error_confirm_empty': 'Vui lòng xác nhận mật khẩu.',
      'register_error_confirm_mismatch': 'Mật khẩu xác nhận không khớp.',
      'register_failed': 'Đăng ký thất bại.',
      'cannot_connect_server': 'Không thể kết nối đến server.',
      'final_review': 'Kiểm tra lại',
      'final_review_subtitle':
          'Vui lòng đảm bảo thông tin chính xác\ntrước khi hoàn tất đăng ký.',
      'personal_details': 'THÔNG TIN CÁ NHÂN',
      'edit': 'Sửa',
      'agree_to_terms': 'Tôi đồng ý với ',
      'terms_of_sanctuary': 'Điều khoản của Resort',
      'and_acknowledge':
          ' và\ncông nhận chính sách bảo mật\nvề bảo vệ môi trường.',
      'submit': 'Hoàn tất',
      'home': 'Trang chủ',
      'bookings': 'Đặt phòng',
      'services': 'Dịch vụ',
      'profile': 'Hồ sơ',
      'search': 'Tìm kiếm',
      'welcome': 'CHÀO MỪNG BẠN ĐẾN VỚI THẢO NGUYÊN RESORT',
      'hello': 'Xin chào',
      'rooms': 'Phòng',
      'view_all': 'Xem tất cả',
      'popular_rooms': 'Phòng phổ biến',
      'night': 'đêm',
      'per_night': '/ đêm',
      'booking_history': 'Lịch sử đặt phòng',
      'payment_history': 'Lịch sử thanh toán',
      'about_resort': 'Về Resort',
      'contact_us': 'Liên hệ',
      'location': 'Vị trí',
      'logout': 'Đăng xuất',
      'edit_profile': 'Chỉnh sửa hồ sơ',
      'full_name': 'Họ và tên',
      'email': 'Địa chỉ Email',
      'phone': 'Số điện thoại',
      'dob': 'Ngày sinh',
      'gender': 'Giới tính',
      'address': 'Địa chỉ',
      'cancel': 'Hủy',
      'save': 'Lưu',
      'categories': 'Danh mục',
      'popular_stays': 'Phòng nổi bật',
      'search_hint': 'Tìm kiếm trải nghiệm...',
      'all': 'Tất cả',
      'promotion': 'KHUYẾN MÃI',
      'adults': 'Người lớn',
      'children': 'Trẻ em',
      'amenities': 'TIỆN NGHI',
      'show_less': 'Thu gọn ∧',
      'more_amenities': 'Xem thêm tiện nghi ∨',
      'the_sanctuary_experience': 'TRẢI NGHIỆM TUYỆT VỜI',
      'read_more': 'Xem thêm ˇ',
      'available_rooms': 'PHÒNG TRỐNG',
      'selected': 'đã chọn',
      'choose_room_instruction': 'Chọn phòng bạn muốn đặt',
      'more_room_numbers': 'Xem thêm số phòng ∨',
      'stay_summary': 'TÓM TẮT ĐẶT PHÒNG',
      'edit': 'CHỈNH SỬA',
      'room_charge': 'Tiền phòng',
      'room_numbers': 'Số phòng',
      'children_extra_fee': 'Phụ phí trẻ em',
      'service_fee_taxes': 'Phí dịch vụ & Thuế (10%)',
      'total': 'Tổng cộng',
      'select_date_room_instruction': 'Vui lòng chọn ngày & phòng',
      'select_date_instruction': 'Vui lòng chọn ngày ở',
      'select_room_instruction': 'Vui lòng chọn phòng',
      'max_rooms_error': 'Tối đa chỉ được đặt 2 phòng trong một lần!',
      'no_description': 'Không có mô tả.',
      'no_rooms_available': 'Hiện tại không có phòng trống.',
      'male': 'Nam',
      'female': 'Nữ',
      'other': 'Khác',
      'profile_updated': 'Cập nhật hồ sơ thành công',
      'update_failed': 'Cập nhật thất bại',
      'error_occurred': 'Đã xảy ra lỗi',
      'nights': 'Đêm',
      'change_photo': 'THAY ĐỔI ẢNH',
      'email_address': 'ĐỊA CHỈ EMAIL',
      'phone_number': 'SỐ ĐIỆN THOẠI',
      'date_of_birth': 'NGÀY SINH',
      'required': 'Bắt buộc',
      'email_change_support': 'Liên hệ hỗ trợ để thay đổi email.',
      'select': 'Chọn',
      'my_bookings': 'Đơn hàng của tôi',
      'pending': 'Chờ xử lý',
      'confirmed': 'Đã xác nhận',
      'completed': 'Hoàn thành',
      'no_bookings_found': 'Không tìm thấy đơn hàng',
      'login_to_view_history': 'Vui lòng đăng nhập để xem lịch sử',
      'retry': 'Thử lại',
      'failed_load_bookings': 'Tải đơn hàng thất bại',
      'portfolio_overview': 'TỔNG QUAN CHI TIÊU',
      'total_spent': 'Tổng chi tiêu',
      'all_payments': 'Tất cả giao dịch',
      'last_30_days': '30 ngày qua',
      'refunds': 'Hoàn tiền',
      'no_transactions_found': 'Không tìm thấy giao dịch',
      'failed_load_rooms': 'Tải danh sách phòng thất bại',
      'all_rooms': 'Tất cả phòng',
      'no_rooms_found': 'Không tìm thấy phòng',
      'adjust_filters': 'Hãy thử điều chỉnh bộ lọc của bạn',
      'resort_services': 'Dịch vụ Resort',
      'nourish_soul': 'Nuôi dưỡng tâm hồn và giác quan',
      'exclusives': 'ĐẶC QUYỀN',
      'curated_experiences': 'Trải nghiệm chọn lọc',
      'hall': 'Hội trường',
      'food': 'Ẩm thực',
      'event': 'Sự kiện',
      'hall_desc': 'Phòng tiệc lớn & phòng hội nghị',
      'food_desc': 'Ẩm thực tinh tế & đặc sản địa phương',
      'event_desc': 'Đám cưới, tiệc tùng & lễ hội',
      'other_services_desc': 'Tour hướng dẫn & hoạt động đặc biệt',
      'hall_cap': 'Lên đến 500 khách',
      'food_cap': 'Trải nghiệm ẩm thực thượng hạng',
      'event_cap': 'Sắp xếp theo yêu cầu',
      'other_cap': 'Khám phá mỗi ngày',
      'check_in': 'Nhận phòng',
      'check_out': 'Trả phòng',
      'quantity': 'Số lượng',
      'room_price': 'Giá phòng',
      'stay_summary_title': 'chi tiết các dịch vụ đã chọn',
      'qr_pass': 'Mã QR của bạn',
      'voucher_applied': 'MÃ GIẢM GIÁ ĐÃ ÁP DỤNG',
      'taxes_service_fee': 'Thuế & Phí dịch vụ (10%)',
      'total_amount': 'Tổng số tiền',
      'no_booking_data': 'Không tìm thấy dữ liệu đặt phòng',
      'booking_details': 'Chi tiết đặt phòng',
      'digital_checkin_pass': 'THẺ NHẬN PHÒNG ĐIỆN TỬ',
      'accommodation_details': 'Chi tiết lưu trú',
      'billing_summary': 'Tóm tắt thanh toán',
      'pricing_summary': 'Tóm tắt giá',
      'primary_guest': 'KHÁCH HÀNG',
      'modify_booking': 'CHỈNH SỬA ĐẶT PHÒNG',
      'cancellation_policy': 'Hủy phòng miễn phí đến',
      'loyalty_points_label': 'ĐIỂM TÍCH LŨY',
      'total_stays_label': 'SỐ PHÒNG ĐÃ ĐẶT',
      'management': 'QUẢN LÝ',
      'others': 'KHÁC',
      'resort_info': 'THÔNG TIN RESORT',
      'contact': 'Liên hệ',
      'get_in_touch': 'LIÊN HỆ VỚI CHÚNG TÔI',
      'call_now': 'Gọi ngay',
      'send_email': 'Gửi Email',
      'inquiry_form': 'Đơn yêu cầu',
      'submit_inquiry': 'Gửi yêu cầu',
      'your_message': 'LỜI NHẮN CỦA BẠN',
      'resort_address': 'ĐỊA CHỈ RESORT',
      'our_sanctuary': 'VỊ TRÍ CỦA CHÚNG TÔI',
      'get_directions': 'Chỉ đường',
      'open_google_maps': 'Mở trong Google Maps',
      'request_pickup': 'Yêu cầu đưa đón',
      'from': 'Chỉ từ',
      'twin': 'Phòng đơn',
      'double': 'Phòng đôi',
      'triple': 'Phòng ba',
      'villa': 'Villa',
      'no_results_found': 'Không tìm thấy kết quả',
      'about_service': 'Về dịch vụ',
      'service_packages': 'Gói dịch vụ',
      'atmosphere': 'Không gian',
      'grand_venue': 'KHÔNG GIAN SANG TRỌNG',
      'premium_service': 'DỊCH VỤ CAO CẤP',
      'book_service': 'Đặt dịch vụ',
      'total_estimate': 'TỔNG ƯỚC TÍNH',
      'guests_label': 'Khách',
      'daily_hourly': 'Theo ngày / Giờ',
      'flexible_timing': 'Thời gian linh hoạt',
      'unlimited': 'Không giới hạn',
      'full_day_pkg': 'Gói trọn ngày',
      'half_day_pkg': 'Gói nửa ngày',
      'standard_unit': 'Gói tiêu chuẩn',
      'per': 'Mỗi',
      'choose_date': 'Chọn ngày',
      'popular': 'Phổ biến nhất',
      'above_12': 'Trên 12 tuổi',
      'below_12': 'Dưới 12 tuổi',
      'child_age_label': 'ĐỘ TUỔI TRẺ EM {n}',
      'age_less_6': 'Dưới 6 tuổi',
      'age_6_12': 'Từ 6 - 12 tuổi',
      'age_more_12': 'Trên 12 tuổi',
      'continue': 'Tiếp tục',
      'max_capacity_reached': 'Đã đạt tối đa {max} {label}',
      'edit_booking': 'Chỉnh sửa đặt phòng',
      'current_reservation': 'ĐẶT CHỖ HIỆN TẠI',
      'select_dates': 'CHỌN NGÀY',
      'select_dates_error': 'Vui lòng chọn ngày Check-in và Check-out!',
      'extra_fee_breakfast_note': '*Phụ phí trẻ em đã bao gồm bữa sáng.',
      'update_booking': 'Cập nhật đặt phòng',
      'premium_eco_luxury': 'KHU NGHỈ DƯỠNG SINH THÁI CAO CẤP',
      'resort_tagline':
          'Một thiên đường ẩn mình giữa những sườn đồi xanh mướt của cao nguyên Mộc Châu, nơi sương sớm hòa quyện cùng thiết kế sang trọng đầy tinh tế.',
      'resort_philosophy':
          'Chúng tôi luôn tin tưởng rằng "The Digital Conservatory" — cuộc sống hiện đại nên tồn tại hài hòa với thế giới tự nhiên. Tại Thảo Nguyên Resort, chúng tôi đã thay thế những ranh giới cứng nhắc bằng những không gian mềm mại và vật liệu bền vững, phản chiếu vẻ đẹp của miền Bắc Việt Nam.\n\nHãy trải nghiệm sự sang trọng tĩnh lặng của vùng cao, nơi mọi chi tiết đều được chăm chút để mang lại một nơi trú ẩn tách biệt khỏi những ồn ào của thế giới bên ngoài.',
      'nature_inspired_title': 'Thiết kế lấy cảm hứng từ thiên nhiên',
      'nature_inspired_desc':
          'Kiến trúc hòa quyện cùng núi rừng, sử dụng gỗ và đá địa phương để phản chiếu địa hình tự nhiên ở nơi đây.',
      'premium_services_title': 'Dịch vụ cao cấp',
      'premium_services_desc':
          'Dịch vụ chăm sóc tận tâm và trải nghiệm ẩm thực địa phương độc đáo, tôn vinh những nét văn hóa của con người và cuộc sống nơi đây.',
      'peaceful_atmosphere_title': 'Không gian yên bình',
      'peaceful_atmosphere_desc':
          'Thao nguyen Resort được thiết kế để hiện ra như một bản giao hưởng dịu dàng của mây trời và cỏ cây, nơi thời gian như ngừng lại để nhường chỗ cho sự tĩnh lặng tuyệt đối và cảm giác thư thái đến tận cùng tâm hồn.',
      'amenities_overview': 'TỔNG QUAN TIỆN NGHI',
      'infinity_pool': 'Bể bơi bốn mùa',
      'infinity_pool_desc': 'Nước khoáng nóng từ nguồn núi',
      'organic_dining': 'Ẩm thực hữu cơ',
      'highland_spa': 'Spa Cao Nguyên',
      'mountain_biking': 'Đạp xe leo núi miễn phí',
      'contact_headline': 'Chúng tôi ở đây\nđể giúp bạn tìm thấy\nsự bình yên.',
      'inquiry_form_subtitle':
          'Hãy để lại lời nhắn và nhân viên hỗ trợ của chúng tôi sẽ liên hệ với bạn ngay lập tức.',
      'message_hint': 'Chúng tôi có thể hỗ trợ gì cho kỳ nghỉ của bạn?',
      'location_headline': 'Mộc Châu, Sơn La,\nViệt Nam',
      'location_desc':
          'Ẩn mình giữa cao nguyên sương mù phía Bắc Việt Nam, bao quanh bởi những đồi chè xanh mướt và hoa mận trắng muốt.',
      'highland_access': 'Đường lên cao nguyên',
      'travel_time': 'Cách Hà Nội 4 giờ di chuyển',
      'find_sanctuary': 'Tìm kiếm phòng',
      'reset': 'ĐẶT LẠI',
      'your_stay': 'KỲ NGHỈ CỦA BẠN',
      'checkin_out': 'Ngày nhận & Trả phòng',
      'arrival': 'NGÀY ĐẾN',
      'departure': 'NGÀY ĐI',
      'select_date': 'Chọn ngày',
      'capacity': 'SỨC CHỨA',
      'num_guests': 'Số lượng khách',
      'ages_13_above': 'Từ 13 tuổi trở lên',
      'ages_2_12': 'Từ 2 - 12 tuổi',
      'zone': 'Khu vực',
      'all_zones': 'Tất cả khu vực',
      'investment': 'MỨC GIÁ',
      'price_range': 'Khoảng giá',
      'minimum': 'TỐI THIỂU',
      'maximum': 'TỐI ĐA',
      'search_sanctuaries': 'TÌM KIẾM PHÒNG',
      'search_error_msg':
          'Vui lòng chọn ngày Check-in, Check-out và số người lớn!',
      'failed_load_rooms': 'Tải danh sách phòng thất bại',
      'no_rooms_found': 'Không tìm thấy phòng',
      'adjust_filters': 'Vui lòng điều chỉnh bộ lọc',
      'found_n_sanctuaries': 'Tìm thấy {n} phòng',
      'filter': 'BỘ LỌC',
      'price': 'GIÁ',
      'filters': 'Bộ lọc',
      'clear_all': 'Xóa tất cả',
      'room_type': 'LOẠI PHÒNG',
      'all_room_types': 'Tất cả loại phòng',
      'apply_filters': 'Áp dụng',
      'left_count': 'CÒN {n} PHÒNG',
      'adults_count': '{n} Người lớn',
      'children_count': '{n} Trẻ em',
      'select_services': 'Chọn dịch vụ',
      'no_services_available': 'Không có dịch vụ nào khả dụng.',
      'no_dates_selected': 'Chưa chọn ngày',
      'from_price_unit': 'Từ {price} VND / {unit}',
      'stay_summary_title': 'TÓM TẮT KỲ NGHỈ',
      'room_charge_n_nights': 'Tiền phòng ({n_rooms} phòng × {n_nights} đêm)',
      'room_numbers': 'Số phòng',
      'children_extra_fee': 'Phụ phí trẻ em',
      'services_total': 'Tổng tiền dịch vụ',
      'service_fee_tax': 'Phí dịch vụ & Thuế (10%)',
      'final_amount': 'TỔNG SỐ TIỀN',
      'continue': 'Tiếp tục',
      'review_booking': 'Kiểm tra đặt phòng',
      'selected_retreat': 'PHÒNG ĐÃ CHỌN',
      'from_2pm': 'từ 14:00',
      'until_12pm': 'trước 12:00',
      'travelers_accommodation': 'KHÁCH & PHÒNG NGHỈ',
      'n_rooms_count': '{n} Phòng',
      'n_rooms_count_plural': '{n} Phòng',
      'selected_services_title': 'DỊCH VỤ ĐÃ CHỌN',
      'quantity': 'Số lượng',
      'price_breakdown': 'CHI TIẾT GIÁ',
      'discount_code': 'MÃ GIẢM GIÁ',
      'enter_code': 'Nhập mã',
      'apply': 'ÁP DỤNG',
      'applied': 'ĐÃ ÁP DỤNG',
      'terms_disclaimer':
          'Bằng cách nhấn "Tiếp tục", bạn đồng ý với Điều khoản dịch vụ và Chính sách hủy phòng của Thảo Nguyên Resort.',
      'voucher_applied_msg': 'Áp dụng mã thành công',
      'invalid_voucher_msg': 'Mã không hợp lệ',
      'discount_label': 'Giảm giá ({code})',
      'total_amount_label': 'Tổng cộng',
      'select_payment_method': 'CHỌN PHƯƠNG THỨC THANH TOÁN',
      'bank_transfer': 'Chuyển khoản ngân hàng',
      'instant_local_transfer': 'Chuyển khoản nội bộ nhanh',
      'e_wallet': 'Ví điện tử',
      'credit_card': 'Thẻ tín dụng',
      'cash_label': 'Tiền mặt',
      'pay_at_front_desk': 'Thanh toán tại quầy lễ tân',
      'secure_checkout': 'THANH TOÁN AN TOÀN & BẢO MẬT',
      'coming_soon': 'Sắp ra mắt',
      'pay_now': 'Thanh toán ngay',
      'failed_create_booking': 'Tạo đơn đặt phòng thất bại',
      'terms_of_use': 'Điều khoản sử dụng',
      'pay_now_agreement': 'Bằng cách nhấn "Thanh toán ngay", bạn đồng ý với ',
      'room_number_label': 'Số phòng: {n}',
      'n_rooms_m_nights': '{n} phòng ({m} đêm)',
      'room_number_label': 'Số phòng: {n}',
      'n_rooms_m_nights': '{n} phòng ({m} đêm)',
      'service_tax_label': 'Thuế & Phí dịch vụ (10%)',
      'room_label': 'Phòng',
      'room_price_label': 'Giá phòng',
      'booking_confirmed': 'Đã xác nhận đặt phòng!',
      'sanctuary_awaits': 'Không gian nghỉ dưỡng đang chờ bạn.',
      'reservation_id_label': 'MÃ ĐẶT PHÒNG',
      'paid_status': 'ĐÃ THANH TOÁN',
      'view_booking_btn': 'Xem chi tiết đặt phòng',
      'back_to_home_btn': 'Về trang chủ',
      'secure_reservation_system': 'HỆ THỐNG ĐẶT PHÒNG BẢO MẬT',
      'resort_service_label': 'Thao Nguyen Resort • Dịch vụ',
      'resort_nights_label': 'Thao Nguyen Resort • {n} Đêm',
      'service_booking_date': 'Ngày đặt dịch vụ',
      'num_portions': 'Số suất',
      'select_portions_instruction': 'Vui lòng chọn số suất ăn',
      'confirm_booking_btn': 'XÁC NHẬN ĐẶT DỊCH VỤ',
      'secure_payment_msg': 'THANH TOÁN AN TOÀN QUA SANCTUARYPAY',
      'server_error_msg': 'Lỗi kết nối server',
      'total_price': 'Tổng giá tiền',
      'resort_room': 'Phòng Resort',
      'resort_service': 'Dịch vụ Resort',
      'service_details': 'Chi tiết dịch vụ',
      'extra_services_included': 'Dịch vụ đặt kèm',
      'quantity_portions': 'Số lượng/Suất',
      'unit_price': 'Đơn giá',
      'amount_label': 'Thành tiền',
      'subtotal_label': 'Tạm tính',
      'room_number_label': 'Số phòng',
      'portfolio_overview': 'TỔNG QUAN CHI TIÊU',
      'total_spent': 'Tổng chi tiêu',
      'all_payments': 'Tất cả',
      'last_30_days': '30 ngày qua',
      'refunds': 'Hoàn tiền',
      'no_transactions_found': 'Chưa có giao dịch nào',
      'paid_status': 'ĐÃ THANH TOÁN',
      'failed_status': 'THẤT BẠI',
      'refunded_status': 'ĐÃ HOÀN TIỀN',
      'account_preferences': 'TÙY CHỌN TÀI KHOẢN',
    },
  };

  static String get(BuildContext context, String key) {
    final locale = Localizations.localeOf(context).languageCode;
    return _localizedValues[locale]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}
