import 'package:flutter/material.dart';

class AppStrings {
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'settings': 'Settings',
      'language': 'Language',
      'choose_dialect': 'Choose your preferred dialect',
      'notifications': 'Notifications',
      'dark_mode': 'Dark Mode',
      'save_changes': 'Save Changes',
      'settings_saved': 'Settings saved successfully',
      'skip': 'Skip',
      'next': 'Next',
      'get_started': 'Get Started',
      'onboarding1_title1': 'Welcome to\n',
      'onboarding1_title2': 'Thao Nguyen\nResort',
      'onboarding1_desc': 'Experience the mist-veiled sanctuary of Moc Chau, where the lush tea hills meet eco-luxury comfort.',
      'onboarding2_title': 'Luxury in Harmony\nwith Nature',
      'onboarding2_desc': 'Enjoy world-class services amidst green\nlandscapes.',
      'onboarding3_title': 'Seamless\nExperience',
      'onboarding3_desc': 'Book your stay and pay securely with\nMoMo in just a few taps.',
      'welcome_back': 'Welcome Back',
      'login_subtitle': 'Enter your credentials to access your sanctuary.',
      'phone_email_label': 'PHONE NUMBER OR EMAIL',
      'email_hint': 'e.g., Example@email.com',
      'password_label': 'PASSWORD',
      'password_hint': 'Enter password',
      'forgot_password': 'Forgot password?',
      'login': 'Login',
      'or_continue_with': 'OR CONTINUE WITH',
      'login_with_google': 'Login with Google',
      'no_account': "Don't have an account? ",
      'register': 'Register',
      'login_error_email_empty': 'Please enter email or phone number.',
      'login_error_email_invalid': 'Invalid email or phone number format.',
      'login_error_password_empty': 'Please enter password.',
      'login_error_password_short': 'Password must be at least 8 characters.',
      'login_failed': 'Login failed.',
      'cannot_connect_server': 'Cannot connect to server. Please try again.',
      'verify_account_title': 'Verify Account',
      'verify_account_msg': 'Your account is not verified.\nPlease verify your account to continue.',
      'cancel': 'Cancel',
      'verify_now': 'Verify Now',
      'step_x_of_3': 'STEP {step} OF 3',
      'create_account': 'Create\nAccount',
      'register_subtitle': 'Begin your journey into the Moc Chau sanctuary. Your forest hideaway awaits.',
      'full_name_label': 'FULL NAME',
      'full_name_hint': 'Enter Full Name',
      'email_address_label': 'EMAIL ADDRESS',
      'phone_number_label': 'PHONE NUMBER',
      'phone_hint': '+84 000 000 000',
      'already_have_account': 'Already have an account? ',
      'log_in': 'LOG IN',
      'secure_your_stay': 'Secure your\nstay.',
      'password_subtitle': 'Choose a password to protect your account\nand bookings.',
      'confirm_password_label': 'CONFIRM PASSWORD',
      're_enter_password_hint': 'Re-enter password',
      'char_8_plus': '8+ Characters',
      'special_symbol': 'Special symbol',
      'save_for_later': 'SAVE FOR LATER',
      'register_error_name_empty': 'Please enter your full name.',
      'register_error_name_invalid': 'Full name can only contain letters and spaces.',
      'register_error_email_empty': 'Please enter your email.',
      'register_error_email_invalid': 'Invalid email format.',
      'register_error_phone_empty': 'Please enter your phone number.',
      'register_error_phone_invalid': 'Phone number must start with 0 or +84 and have 10 digits.',
      'register_error_password_empty': 'Please enter a password.',
      'register_error_password_short': 'Password must be at least 8 characters long.',
      'register_error_password_special': 'Password must contain at least one special character.',
      'register_error_confirm_empty': 'Please confirm your password.',
      'register_error_confirm_mismatch': 'Confirm password does not match.',
      'register_failed': 'Registration failed.',
      'cannot_connect_server': 'Cannot connect to server.',
      'final_review': 'Final Review',
      'final_review_subtitle': 'Please ensure all details are correct\nbefore finalizing your membership.',
      'personal_details': 'PERSONAL DETAILS',
      'edit': 'Edit',
      'agree_to_terms': 'I agree to the ',
      'terms_of_sanctuary': 'Terms of Sanctuary',
      'and_acknowledge': ' and\nacknowledge the privacy policy\nregarding forest conservation.',
      'submit': 'Submit',
      'home': 'Home',
      'bookings': 'Bookings',
      'services': 'Services',
      'profile': 'Profile',
      'search': 'Search',
      'welcome': 'WELCOME TO THE HIGHLANDS',
      'hello': 'Hello',
      'rooms': 'Rooms',
      'view_all': 'View All',
      'popular_rooms': 'Popular Rooms',
      'night': 'night',
      'per_night': '/ night',
      'booking_history': 'Booking History',
      'payment_history': 'Payment History',
      'about_resort': 'About Resort',
      'contact_us': 'Contact Us',
      'location': 'Location',
      'logout': 'Logout',
      'edit_profile': 'Edit Profile',
      'full_name': 'Full Name',
      'email': 'Email Address',
      'phone': 'Phone Number',
      'dob': 'Date of Birth',
      'gender': 'Gender',
      'address': 'Address',
      'cancel': 'Cancel',
      'save': 'Save',
      'categories': 'Categories',
      'popular_stays': 'Popular Stays',
      'search_hint': 'Search experiences...',
      'all': 'All',
      'promotion': 'PROMOTION',
      'adults': 'Adults',
      'children': 'Children',
      'amenities': 'AMENITIES',
      'show_less': 'Show less ∧',
      'more_amenities': 'More amenities ∨',
      'the_sanctuary_experience': 'THE SANCTUARY EXPERIENCE',
      'read_more': 'Read more ˇ',
      'available_rooms': 'AVAILABLE ROOMS',
      'selected': 'selected',
      'choose_room_instruction': 'Choose the room you want to book',
      'more_room_numbers': 'More room numbers ∨',
      'stay_summary': 'STAY SUMMARY',
      'edit': 'EDIT',
      'room_charge': 'Room Charge',
      'room_numbers': 'Room Numbers',
      'children_extra_fee': 'Children Extra Fee',
      'service_fee_taxes': 'Service Fee & Taxes (10%)',
      'total': 'Total',
      'select_date_room_instruction': 'Please select dates & rooms',
      'select_date_instruction': 'Please select stay dates',
      'select_room_instruction': 'Please select a room',
      'max_rooms_error': 'Maximum 2 rooms can be booked at once!',
      'no_description': 'No description available.',
      'no_rooms_available': 'Currently no rooms available.',
      'male': 'Male',
      'female': 'Female',
      'other': 'Other',
      'profile_updated': 'Profile updated successfully',
      'update_failed': 'Update failed',
      'error_occurred': 'An error occurred',
      'nights': 'Nights',
      'change_photo': 'CHANGE PHOTO',
      'email_address': 'EMAIL ADDRESS',
      'phone_number': 'PHONE NUMBER',
      'date_of_birth': 'DATE OF BIRTH',
      'required': 'Required',
      'email_change_support': 'Contact support to change verified email.',
      'select': 'Select',
      'my_bookings': 'My Bookings',
      'pending': 'Pending',
      'confirmed': 'Confirmed',
      'completed': 'Completed',
      'no_bookings_found': 'No bookings found',
      'login_to_view_history': 'Please login to view booking history',
      'retry': 'Retry',
      'failed_load_bookings': 'Failed to load bookings',
      'portfolio_overview': 'PORTFOLIO OVERVIEW',
      'total_spent': 'Total Spent',
      'all_payments': 'All Payments',
      'last_30_days': 'Last 30 Days',
      'refunds': 'Refunds',
      'no_transactions_found': 'No transactions found',
      'failed_load_rooms': 'Failed to load rooms',
      'all_rooms': 'All rooms',
      'no_rooms_found': 'No rooms found',
      'adjust_filters': 'Try adjusting your filters',
      'resort_services': 'Resort Services',
      'nourish_soul': 'Nourish your soul and senses',
      'exclusives': 'EXCLUSIVES',
      'curated_experiences': 'Curated Experiences',
      'hall': 'Hall',
      'food': 'Food',
      'event': 'Event',
      'hall_desc': 'Grand ballroom & conference rooms',
      'food_desc': 'Fine dining & local specialties',
      'event_desc': 'Weddings, parties & festivals',
      'other_services_desc': 'Guided tours & special activities',
      'hall_cap': 'Up to 500 guests',
      'food_cap': 'Gourmet experience',
      'event_cap': 'Custom arrangements',
      'other_cap': 'Daily adventures',
      'check_in': 'Check-in',
      'check_out': 'Check-out',
      'quantity': 'Quantity',
      'room_price': 'Room Price',
      'stay_summary_title': 'Your Stay Summary',
      'qr_pass': 'Your QR Pass',
      'voucher_applied': 'VOUCHER APPLIED',
      'taxes_service_fee': 'Taxes & Service Fee (10%)',
      'total_amount': 'Total Amount',
      'no_booking_data': 'No booking data found',
      'booking_details': 'Booking Details',
      'digital_checkin_pass': 'DIGITAL CHECK-IN PASS',
      'accommodation_details': 'Accommodation Details',
      'billing_summary': 'Billing Summary',
      'pricing_summary': 'Pricing Summary',
      'primary_guest': 'PRIMARY GUEST',
      'modify_booking': 'MODIFY BOOKING',
      'cancellation_policy': 'Free cancellation until',
      'loyalty_points_label': 'LOYALTY POINTS',
      'total_stays_label': 'TOTAL STAYS',
      'management': 'MANAGEMENT',
      'others': 'OTHERS',
      'resort_info': 'RESORT INFO',
      'contact': 'Contact',
      'get_in_touch': 'GET IN TOUCH',
      'call_now': 'Call Now',
      'send_email': 'Send Email',
      'inquiry_form': 'Inquiry Form',
      'submit_inquiry': 'Submit Inquiry',
      'your_message': 'YOUR MESSAGE',
      'resort_address': 'RESORT ADDRESS',
      'our_sanctuary': 'OUR SANCTUARY',
      'get_directions': 'Get Directions',
      'open_google_maps': 'Open in Google Maps',
      'request_pickup': 'Request Pickup',
      'from': 'From',
      'twin': 'Twin',
      'double': 'Double',
      'triple': 'Triple',
      'villa': 'Villa',
      'no_results_found': 'No results found',
      'about_service': 'About the Service',
      'service_packages': 'Service Packages',
      'atmosphere': 'Atmosphere',
      'grand_venue': 'GRAND VENUE',
      'premium_service': 'PREMIUM SERVICE',
      'book_service': 'Book Service',
      'total_estimate': 'TOTAL ESTIMATE',
      'guests_label': 'Guests',
      'daily_hourly': 'Daily / Hourly',
      'flexible_timing': 'Flexible Timing',
      'unlimited': 'Unlimited',
      'full_day_pkg': 'Full Day Package',
      'half_day_pkg': 'Half Day Package',
      'standard_unit': 'Standard Unit',
      'per': 'Per',
      'choose_date': 'Choose Date',
      'popular': 'Popular',
    },
    'vi': {
      'settings': 'Cài đặt',
      'language': 'Ngôn ngữ',
      'choose_dialect': 'Chọn ngôn ngữ bạn muốn sử dụng',
      'notifications': 'Thông báo',
      'dark_mode': 'Chế độ tối',
      'save_changes': 'Lưu thay đổi',
      'settings_saved': 'Đã lưu cài đặt thành công',
      'skip': 'Bỏ qua',
      'next': 'Tiếp tục',
      'get_started': 'Bắt đầu ngay',
      'onboarding1_title1': 'Chào mừng bạn đến với\n',
      'onboarding1_title2': 'Thao Nguyen\nResort',
      'onboarding1_desc': 'Trải nghiệm không gian nghỉ dưỡng sương mờ tại Mộc Châu, nơi đồi chè xanh mướt gặp gỡ sự tiện nghi sang trọng.',
      'onboarding2_title': 'Sự sang trọng hòa quyện\ncùng thiên nhiên',
      'onboarding2_desc': 'Tận hưởng dịch vụ đẳng cấp thế giới giữa\ncảnh quan xanh tươi.',
      'onboarding3_title': 'Trải nghiệm\nmượt mà',
      'onboarding3_desc': 'Đặt phòng và thanh toán an toàn qua\nMoMo chỉ với vài thao tác.',
      'welcome_back': 'Chào mừng trở lại',
      'login_subtitle': 'Nhập thông tin của bạn để truy cập vào không gian nghỉ dưỡng.',
      'phone_email_label': 'SỐ ĐIỆN THOẠI HOẶC EMAIL',
      'email_hint': 'Ví dụ: Example@email.com',
      'password_label': 'MẬT KHẨU',
      'password_hint': 'Nhập mật khẩu',
      'forgot_password': 'Quên mật khẩu?',
      'login': 'Đăng nhập',
      'or_continue_with': 'HOẶC TIẾP TỤC VỚI',
      'login_with_google': 'Đăng nhập với Google',
      'no_account': 'Chưa có tài khoản? ',
      'register': 'Đăng ký',
      'login_error_email_empty': 'Vui lòng nhập email hoặc số điện thoại.',
      'login_error_email_invalid': 'Email hoặc số điện thoại không đúng định dạng.',
      'login_error_password_empty': 'Vui lòng nhập mật khẩu.',
      'login_error_password_short': 'Mật khẩu phải có ít nhất 8 ký tự.',
      'login_failed': 'Đăng nhập thất bại.',
      'cannot_connect_server': 'Không thể kết nối đến server. Vui lòng thử lại.',
      'verify_account_title': 'Xác thực tài khoản',
      'verify_account_msg': 'Tài khoản của bạn chưa được xác thực.\nVui lòng xác thực tài khoản để tiếp tục.',
      'cancel': 'Hủy',
      'verify_now': 'Xác thực ngay',
      'step_x_of_3': 'BƯỚC {step} / 3',
      'create_account': 'Tạo\nTài khoản',
      'register_subtitle': 'Bắt đầu hành trình của bạn tại Mộc Châu. Nơi nghỉ dưỡng giữa rừng đang chờ đón bạn.',
      'full_name_label': 'HỌ VÀ TÊN',
      'full_name_hint': 'Nhập họ và tên',
      'email_address_label': 'ĐỊA CHỈ EMAIL',
      'phone_number_label': 'SỐ ĐIỆN THOẠI',
      'phone_hint': '+84 000 000 000',
      'already_have_account': 'Đã có tài khoản? ',
      'log_in': 'ĐĂNG NHẬP',
      'secure_your_stay': 'Bảo mật\ntài khoản.',
      'password_subtitle': 'Chọn mật khẩu để bảo vệ tài khoản\nvà các thông tin đặt phòng của bạn.',
      'confirm_password_label': 'XÁC NHẬN MẬT KHẨU',
      're_enter_password_hint': 'Nhập lại mật khẩu',
      'char_8_plus': '8+ ký tự',
      'special_symbol': 'Ký tự đặc biệt',
      'save_for_later': 'LƯU ĐỂ SAU',
      'register_error_name_empty': 'Vui lòng nhập họ tên.',
      'register_error_name_invalid': 'Họ tên chỉ chứa chữ cái và dấu cách.',
      'register_error_email_empty': 'Vui lòng nhập email.',
      'register_error_email_invalid': 'Email không đúng định dạng.',
      'register_error_phone_empty': 'Vui lòng nhập số điện thoại.',
      'register_error_phone_invalid': 'SĐT phải bắt đầu bằng 0 hoặc +84, gồm 10 số.',
      'register_error_password_empty': 'Vui lòng nhập mật khẩu.',
      'register_error_password_short': 'Mật khẩu phải có ít nhất 8 ký tự.',
      'register_error_password_special': 'Mật khẩu phải chứa ít nhất 1 ký tự đặc biệt.',
      'register_error_confirm_empty': 'Vui lòng xác nhận mật khẩu.',
      'register_error_confirm_mismatch': 'Mật khẩu xác nhận không khớp.',
      'register_failed': 'Đăng ký thất bại.',
      'cannot_connect_server': 'Không thể kết nối đến server.',
      'final_review': 'Kiểm tra lại',
      'final_review_subtitle': 'Vui lòng đảm bảo thông tin chính xác\ntrước khi hoàn tất đăng ký.',
      'personal_details': 'THÔNG TIN CÁ NHÂN',
      'edit': 'Sửa',
      'agree_to_terms': 'Tôi đồng ý với ',
      'terms_of_sanctuary': 'Điều khoản của Resort',
      'and_acknowledge': ' và\ncông nhận chính sách bảo mật\nvề bảo vệ môi trường.',
      'submit': 'Hoàn tất',
      'home': 'Trang chủ',
      'bookings': 'Đặt phòng',
      'services': 'Dịch vụ',
      'profile': 'Hồ sơ',
      'search': 'Tìm kiếm',
      'welcome': 'CHÀO MỪNG BẠN ĐẾN VỚI CAO NGUYÊN MỘC CHÂU',
      'hello': 'Xin chào',
      'rooms': 'Phòng',
      'view_all': 'Xem tất cả',
      'popular_rooms': 'Phòng phổ biến',
      'night': 'đêm',
      'per_night': '/ đêm',
      'booking_history': 'Lịch sử đặt phòng',
      'payment_history': 'Lịch sử thanh toán',
      'about_resort': 'Về Resort',
      'contact_us': 'Liên hệ',
      'location': 'Vị trí',
      'logout': 'Đăng xuất',
      'edit_profile': 'Chỉnh sửa hồ sơ',
      'full_name': 'Họ và tên',
      'email': 'Địa chỉ Email',
      'phone': 'Số điện thoại',
      'dob': 'Ngày sinh',
      'gender': 'Giới tính',
      'address': 'Địa chỉ',
      'cancel': 'Hủy',
      'save': 'Lưu',
      'categories': 'Danh mục',
      'popular_stays': 'Phòng nổi bật',
      'search_hint': 'Tìm kiếm trải nghiệm...',
      'all': 'Tất cả',
      'promotion': 'KHUYẾN MÃI',
      'adults': 'Người lớn',
      'children': 'Trẻ em',
      'amenities': 'TIỆN NGHI',
      'show_less': 'Thu gọn ∧',
      'more_amenities': 'Xem thêm tiện nghi ∨',
      'the_sanctuary_experience': 'TRẢI NGHIỆM TUYỆT VỜI',
      'read_more': 'Xem thêm ˇ',
      'available_rooms': 'PHÒNG TRỐNG',
      'selected': 'đã chọn',
      'choose_room_instruction': 'Chọn phòng bạn muốn đặt',
      'more_room_numbers': 'Xem thêm số phòng ∨',
      'stay_summary': 'TÓM TẮT ĐẶT PHÒNG',
      'edit': 'CHỈNH SỬA',
      'room_charge': 'Tiền phòng',
      'room_numbers': 'Số phòng',
      'children_extra_fee': 'Phụ phí trẻ em',
      'service_fee_taxes': 'Phí dịch vụ & Thuế (10%)',
      'total': 'Tổng cộng',
      'select_date_room_instruction': 'Vui lòng chọn ngày & phòng',
      'select_date_instruction': 'Vui lòng chọn ngày ở',
      'select_room_instruction': 'Vui lòng chọn phòng',
      'max_rooms_error': 'Tối đa chỉ được đặt 2 phòng trong một lần!',
      'no_description': 'Không có mô tả.',
      'no_rooms_available': 'Hiện tại không có phòng trống.',
      'male': 'Nam',
      'female': 'Nữ',
      'other': 'Khác',
      'profile_updated': 'Cập nhật hồ sơ thành công',
      'update_failed': 'Cập nhật thất bại',
      'error_occurred': 'Đã xảy ra lỗi',
      'nights': 'Đêm',
      'change_photo': 'THAY ĐỔI ẢNH',
      'email_address': 'ĐỊA CHỈ EMAIL',
      'phone_number': 'SỐ ĐIỆN THOẠI',
      'date_of_birth': 'NGÀY SINH',
      'required': 'Bắt buộc',
      'email_change_support': 'Liên hệ hỗ trợ để thay đổi email.',
      'select': 'Chọn',
      'my_bookings': 'Đơn hàng của tôi',
      'pending': 'Chờ xử lý',
      'confirmed': 'Đã xác nhận',
      'completed': 'Hoàn thành',
      'no_bookings_found': 'Không tìm thấy đơn hàng',
      'login_to_view_history': 'Vui lòng đăng nhập để xem lịch sử',
      'retry': 'Thử lại',
      'failed_load_bookings': 'Tải đơn hàng thất bại',
      'portfolio_overview': 'TỔNG QUAN CHI TIÊU',
      'total_spent': 'Tổng chi tiêu',
      'all_payments': 'Tất cả giao dịch',
      'last_30_days': '30 ngày qua',
      'refunds': 'Hoàn tiền',
      'no_transactions_found': 'Không tìm thấy giao dịch',
      'failed_load_rooms': 'Tải danh sách phòng thất bại',
      'all_rooms': 'Tất cả phòng',
      'no_rooms_found': 'Không tìm thấy phòng',
      'adjust_filters': 'Hãy thử điều chỉnh bộ lọc của bạn',
      'resort_services': 'Dịch vụ Resort',
      'nourish_soul': 'Nuôi dưỡng tâm hồn và giác quan',
      'exclusives': 'ĐẶC QUYỀN',
      'curated_experiences': 'Trải nghiệm chọn lọc',
      'hall': 'Hội trường',
      'food': 'Ẩm thực',
      'event': 'Sự kiện',
      'hall_desc': 'Phòng tiệc lớn & phòng hội nghị',
      'food_desc': 'Ẩm thực tinh tế & đặc sản địa phương',
      'event_desc': 'Đám cưới, tiệc tùng & lễ hội',
      'other_services_desc': 'Tour hướng dẫn & hoạt động đặc biệt',
      'hall_cap': 'Lên đến 500 khách',
      'food_cap': 'Trải nghiệm ẩm thực thượng hạng',
      'event_cap': 'Sắp xếp theo yêu cầu',
      'other_cap': 'Khám phá mỗi ngày',
      'check_in': 'Nhận phòng',
      'check_out': 'Trả phòng',
      'quantity': 'Số lượng',
      'room_price': 'Giá phòng',
      'stay_summary_title': 'Tóm tắt kỳ nghỉ của bạn',
      'qr_pass': 'Mã QR của bạn',
      'voucher_applied': 'MÃ GIẢM GIÁ ĐÃ ÁP DỤNG',
      'taxes_service_fee': 'Thuế & Phí dịch vụ (10%)',
      'total_amount': 'Tổng số tiền',
      'no_booking_data': 'Không tìm thấy dữ liệu đặt phòng',
      'booking_details': 'Chi tiết đặt phòng',
      'digital_checkin_pass': 'THẺ NHẬN PHÒNG ĐIỆN TỬ',
      'accommodation_details': 'Chi tiết lưu trú',
      'billing_summary': 'Tóm tắt thanh toán',
      'pricing_summary': 'Tóm tắt giá',
      'primary_guest': 'KHÁCH HÀNG CHÍNH',
      'modify_booking': 'CHỈNH SỬA ĐẶT PHÒNG',
      'cancellation_policy': 'Hủy phòng miễn phí đến',
      'loyalty_points_label': 'ĐIỂM TÍCH LŨY',
      'total_stays_label': 'SỐ PHÒNG ĐÃ ĐẶT',
      'management': 'QUẢN LÝ',
      'others': 'KHÁC',
      'resort_info': 'THÔNG TIN RESORT',
      'contact': 'Liên hệ',
      'get_in_touch': 'LIÊN HỆ VỚI CHÚNG TÔI',
      'call_now': 'Gọi ngay',
      'send_email': 'Gửi Email',
      'inquiry_form': 'Đơn yêu cầu',
      'submit_inquiry': 'Gửi yêu cầu',
      'your_message': 'LỜI NHẮN CỦA BẠN',
      'resort_address': 'ĐỊA CHỈ RESORT',
      'our_sanctuary': 'VỊ TRÍ CỦA CHÚNG TÔI',
      'get_directions': 'Chỉ đường',
      'open_google_maps': 'Mở trong Google Maps',
      'request_pickup': 'Yêu cầu đưa đón',
      'from': 'Chỉ từ',
      'twin': 'Phòng đơn',
      'double': 'Phòng đôi',
      'triple': 'Phòng ba',
      'villa': 'Villa',
      'no_results_found': 'Không tìm thấy kết quả',
      'about_service': 'Về dịch vụ',
      'service_packages': 'Gói dịch vụ',
      'atmosphere': 'Không gian',
      'grand_venue': 'KHÔNG GIAN SANG TRỌNG',
      'premium_service': 'DỊCH VỤ CAO CẤP',
      'book_service': 'Đặt dịch vụ',
      'total_estimate': 'TỔNG ƯỚC TÍNH',
      'guests_label': 'Khách',
      'daily_hourly': 'Theo ngày / Giờ',
      'flexible_timing': 'Thời gian linh hoạt',
      'unlimited': 'Không giới hạn',
      'full_day_pkg': 'Gói trọn ngày',
      'half_day_pkg': 'Gói nửa ngày',
      'standard_unit': 'Gói tiêu chuẩn',
      'per': 'Mỗi',
      'choose_date': 'Chọn ngày',
      'popular': 'Phổ biến nhất',
    },
  };

  static String get(BuildContext context, String key) {
    final locale = Localizations.localeOf(context).languageCode;
    return _localizedValues[locale]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}
